spring.application.name=authentication

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

spring.security.data.name = data
spring.security.data.password=$2a$12$jRwNn2zhzmaiwD2ljeF70udZrejNg.OPkrruu6dextR1rgrPB0yRC

app.default-role=USER
app.default-enabled=false